// <auto-generated/>
#nullable enable

#if !GEN
namespace Recline;
#endif

[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
public class CommandAttribute : System.Attribute
{
    public string CmdName { get; }
    public string? ShortDesc { get; set; }

    public CommandAttribute(string cmdName) => CmdName = cmdName;

    public void Deconstruct(
        out string cmdName,
        out string? desc
    ) {
        cmdName = CmdName;
        desc = ShortDesc;
    }
}